apiVersion: v1
kind: Pod
metadata:
  name: sentinel-active
  labels:
    app: sentinel-active
spec:
  containers:
  - name: sentinel-active
    image: alwende/sentinel-control:v5.2.0-GOLD
    imagePullPolicy: Always
    ports:
    - containerPort: 9090
      name: metrics
    - containerPort: 5000
      name: webui
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: ENABLE_METRICS
      value: "true"
