apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-core-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentinel-core
  template:
    metadata:
      labels:
        app: sentinel-core
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: grafana-pv-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-pv-storage
        persistentVolumeClaim:
          claimName: grafana-storage
