apiVersion: v1
kind: Secret
metadata:
  name: sentinel-control-secrets
type: Opaque
stringData:
  SLACK_URL: "https://hooks.slack.com/services/REDACTED
  PROMETHEUS_GCP: "http://prometheus-service:9090/api/v1/query"
  GRAFANA_API_KEY: "REDACTED_TOKEN
